# Generated by Django 4.1.3 on 2023-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sex', models.BooleanField(default=1, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('class_null', models.CharField(max_length=5, verbose_name='Class')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'db_table': 'tb_student',
            },
        ),
    ]
